---
swagger: "2.0"
info:
  version: "3.1.1-SNAPSHOT"
  title: "Job Configuration FileLink"
host: "integration.actiandatacloud.com"
schemes:
- "https"
paths:
  /jobconfigs/{id}/filelinks:
    post:
      summary: "Create JobConfig File Link"
      description: ""
      operationId: "createJobConfigFileLink"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/FileLinkRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/FileResponse"
        201:
          description: "Created"
        400:
          description: "bad request"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        409:
          description: "Conflict"
  /jobconfigs/{id}/filelinks/{linkid}:
    delete:
      summary: "Delete Jobconfig File Link"
      description: ""
      operationId: "deleteJobConfigFileLink"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        204:
          description: "No Content"
  /jobtemplates/{id}/filelinks:
    post:
      summary: "Create JobTemplate File Link"
      description: ""
      operationId: "createJobTemplateFileLink"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/FileLinkRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/FileResponse"
        201:
          description: "Created"
        400:
          description: "bad request"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        409:
          description: "Conflict"
  /jobtemplates/{id}/filelinks/{linkid}:
    delete:
      summary: "Delete Jobtemplate File Link"
      description: ""
      operationId: "deleteJobTemplateFileLink"
      produces:
      - "application/json"
      parameters: []
      responses:
        204:
          description: "No Content"
  /{entitytype}/{entityid}/filelinks/{name}:
    get:
      summary: "List All File Links"
      description: ""
      operationId: "listAllFileLinks"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "string"
      - in: "body"
        name: "body"
        description: "Page number (zero based)"
        required: false
        schema:
          type: "string"
      - in: "body"
        name: "body"
        description: "Page size"
        required: false
        schema:
          type: "string"
      - in: "body"
        name: "body"
        description: "Sort by column name"
        required: false
        schema:
          type: "string"
      - in: "body"
        name: "body"
        description: "Sort direction (asc or desc)"
        required: false
        schema:
          type: "string"
      - in: "body"
        name: "body"
        description: "Filter (resource ID)"
        required: false
        schema:
          type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/FileListResponse"
        404:
          description: "Not found"
definitions:
  ApiErrorResponse:
    type: "object"
    properties:
      message:
        type: "string"
  FileLinkRequest:
    type: "object"
    properties:
      entityType:
        type: "string"
        enum:
        - "ACCOUNT"
        - "GROUP"
        - "USER"
        - "PROVISIONING"
        - "LICENSE"
        - "JOBTEMPLATE"
        - "JOBCONFIG"
        - "JOB"
        - "OUTPUT"
        - "TEMP"
        - "AGENT"
        - "NONE"
      entityId:
        type: "string"
      fileName:
        type: "string"
      id:
        type: "string"
  FileListResponse:
    type: "object"
    properties:
      totalRecords:
        type: "integer"
        format: "int64"
      totalPages:
        type: "integer"
        format: "int32"
      size:
        type: "integer"
        format: "int32"
      pageNumber:
        type: "integer"
        format: "int32"
      sortBy:
        type: "string"
      direction:
        type: "string"
      filter:
        type: "string"
      items:
        type: "array"
        items:
          $ref: "#/definitions/FileResponse"
  FileMetaData:
    type: "object"
    properties:
      size:
        type: "integer"
        format: "int64"
      lastModified:
        type: "string"
        format: "date-time"
      entityType:
        type: "string"
        enum:
        - "ACCOUNT"
        - "GROUP"
        - "USER"
        - "PROVISIONING"
        - "LICENSE"
        - "JOBTEMPLATE"
        - "JOBCONFIG"
        - "JOB"
        - "OUTPUT"
        - "TEMP"
        - "AGENT"
        - "NONE"
      entityId:
        type: "string"
      linkType:
        type: "string"
        enum:
        - "LINK"
        - "INHERITED"
        - "LOCAL"
      linkId:
        type: "integer"
        format: "int64"
  FileResponse:
    type: "object"
    properties:
      name:
        type: "string"
      href:
        type: "string"
      metadata:
        $ref: "#/definitions/FileMetaData"
      linkId:
        type: "string"
